logging:
    level:
        ROOT: DEBUG
        sweet.itech.ecommerce: DEBUG


spring:
    profiles:
        active: dev
    devtools:
        restart:
            enabled: true
    jackson:
        serialization.indent_output: true
    datasource:
           driver-class-name: com.mysql.jdbc.Driver
           url: jdbc:mysql://localhost:3306/sweetitech
           username: root
           password: sweetitech
           hikari:
               data-source-properties:
                   cachePrepStmts: true
                   prepStmtCacheSize: 250
                   prepStmtCacheSqlLimit: 2048
                   useServerPrepStmts: true
    jpa:
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
        database: MYSQL
        show-sql: true
        properties:
            hibernate.id.new_generator_mappings: true
            hibernate.cache.use_second_level_cache: true
            hibernate.cache.use_query_cache: false
            hibernate.generate_statistics: true
        hibernate:
            ddl-auto: update


liquibase:
    contexts: dev


server:
    port: 8080



ecommerce:
  security:
    remember-me:
      key: 0bd949b5237b08cad1af51e6737d1266871a4ea8
