version: '2'
 
services:
  mysql:
    image: mysql:5.7
    container_name: mysql-container-compose
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: sweetitech
      MYSQL_DATABASE: sweetitech
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    volumes:
      - C:/Users/monju/Documents/mysql-data/data:/var/lib/mysql